# Generated by Django

from django.db import migrations, models
import knowledge.models.knowledge


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_add_page_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageindexnode',
            name='embedding',
            field=knowledge.models.knowledge.VectorField(null=True, verbose_name='节点向量'),
        ),
        migrations.AddField(
            model_name='pageindexnode',
            name='embedding_status',
            field=models.CharField(
                choices=[('0', 'PENDING'), ('1', 'STARTED'), ('2', 'SUCCESS'), ('3', 'FAILURE'), ('4', 'REVOKE'), ('5', 'REVOKED'), ('n', 'IGNORED')],
                default='0',
                max_length=20,
                verbose_name='嵌入状态'
            ),
        ),
    ]
