# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_add_page_index_embedding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='section_title',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='章节标题'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='section_path',
            field=models.CharField(db_index=True, default='', max_length=1024, verbose_name='章节路径'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='章节摘要'),
        ),
    ]
