# Generated by Django 5.2.9 on 2026-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge",
            "0011_paragraph_page_index_node_alter_document_knowledge_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="embedding",
            name="source_type",
            field=models.CharField(
                choices=[("0", "问题"), ("1", "段落"), ("2", "标题"), ("3", "摘要")],
                db_index=True,
                default="0",
                max_length=5,
                verbose_name="资源类型",
            ),
        ),
    ]
